
// xxx MUST ENSURE THAT ANY STAKE ACCOUNT SUPPLIED ALWAYS HOLDS AT LEAST RENT EXEMPT MINIMUM FOR STAKE ACCOUNTS
// OTHERWISE THE STAKE ACCOUNT COULD "DISAPPEAR".

static uint64_t do_buy_ticket(SolParameters *params)
{
    return 0;
}
